export enum DataNames {
  STATIONS_IN_GROUPS = 'STATIONS_IN_GROUPS',
  MONITOR_THRESHOLDS = 'MONITOR_THRESHOLDS',
  CHANNEL_MONITOR_THRESHOLDS = 'CHANNEL_MONITOR_THRESHOLDS',
  STATION_GROUP_CAPABILITY_ROLLUP = 'STATION_GROUP_CAPABILITY_ROLLUP',
  STATION_CAPABILITY_ROLLUP = 'STATION_CAPABILITY_ROLLUP',
  CHANNEL_CAPABILITY_ROLLUP = 'CHANNEL_CAPABILITY_ROLLUP',
  TIMEWINDOWS = 'TIME_WINDOWS',
  STATION_GROUPS = 'STATION_GROUPS',
  STATION_ENV_MONITOR_TYPES = 'STATION_ENV_MONITOR_TYPES',
  SYNC_DEPLOYMENT_WITH_PROCESSING = 'SYNC_DEPLOYMENT_WITH_PROCESSING',
}

// Used for drag and drop options
export const ItemTypes = {
  GROUP: 'GROUP',
};
